import type { Job } from "@/types/job";

export const jobsData: Job[] = [
  {
    id: 1,
    title: "Frontend React Developer",
    company: "Último rol en Andes Tech",
    city: "Bogotá",
    mode: "Híbrido",
    salary: "$6.500.000 - $8.000.000 COP",
    category: "Tecnología",
    seniority: "Mid",
    featured: true,
  },
  {
    id: 2,
    title: "Product Designer UX/UI",
    company: "Último rol en Nativo Digital",
    city: "Medellín",
    mode: "Remoto",
    salary: "$5.200.000 - $7.000.000 COP",
    category: "Diseño",
    seniority: "Senior",
    featured: true,
  },
  {
    id: 3,
    title: "Especialista en Performance Marketing",
    company: "Último rol en Impulso Ads",
    city: "Bogotá",
    mode: "Híbrido",
    salary: "$4.800.000 - $6.200.000 COP",
    category: "Marketing",
    seniority: "Mid",
    featured: false,
  },
  {
    id: 4,
    title: "Account Executive B2B",
    company: "Último rol en Comercial Norte",
    city: "Barranquilla",
    mode: "Presencial",
    salary: "$4.000.000 - $5.300.000 COP",
    category: "Ventas",
    seniority: "Junior",
    featured: false,
  },
  {
    id: 5,
    title: "Agente de Soporte al Cliente",
    company: "Último rol en SoporteYA",
    city: "Cali",
    mode: "Remoto",
    salary: "$2.800.000 - $3.600.000 COP",
    category: "Atención al cliente",
    seniority: "Junior",
    featured: false,
  },
  {
    id: 6,
    title: "Backend Node.js Engineer",
    company: "Último rol en Páramo Cloud",
    city: "Medellín",
    mode: "Híbrido",
    salary: "$7.000.000 - $9.200.000 COP",
    category: "Tecnología",
    seniority: "Senior",
    featured: true,
  },
  {
    id: 7,
    title: "Diseñador de Marca",
    company: "Último rol en Brava Studio",
    city: "Bogotá",
    mode: "Presencial",
    salary: "$4.300.000 - $5.600.000 COP",
    category: "Diseño",
    seniority: "Mid",
    featured: false,
  },
  {
    id: 8,
    title: "Social Media Manager",
    company: "Último rol en Cacao Creativo",
    city: "Cali",
    mode: "Híbrido",
    salary: "$3.900.000 - $5.200.000 COP",
    category: "Marketing",
    seniority: "Mid",
    featured: false,
  },
  {
    id: 9,
    title: "Sales Development Representative",
    company: "Último rol en Orbita SaaS",
    city: "Bogotá",
    mode: "Remoto",
    salary: "$3.600.000 - $4.800.000 COP",
    category: "Ventas",
    seniority: "Junior",
    featured: true,
  },
  {
    id: 10,
    title: "Líder de Customer Success",
    company: "Último rol en Talento Grid",
    city: "Medellín",
    mode: "Remoto",
    salary: "$5.800.000 - $7.200.000 COP",
    category: "Atención al cliente",
    seniority: "Senior",
    featured: true,
  },
  {
    id: 11,
    title: "Analista Financiero",
    company: "Último rol en Ruta Capital",
    city: "Bogotá",
    mode: "Híbrido",
    salary: "$4.900.000 - $6.100.000 COP",
    category: "Finanzas",
    seniority: "Mid",
    featured: false,
  },
  {
    id: 12,
    title: "Growth Marketing Lead",
    company: "Último rol en Launch Colombia",
    city: "Barranquilla",
    mode: "Remoto",
    salary: "$6.200.000 - $8.000.000 COP",
    category: "Marketing",
    seniority: "Senior",
    featured: true,
  },
];
