import { PHRASE_MAP_CORE } from "@/components/ui/auto-ui-translator/phrase-map-core";

export const PHRASE_MAP: Record<string, string> = {
  ...PHRASE_MAP_CORE,
  "Opiniones": "Notes",
  "Máximo 200 caracteres": "Maximum 200 characters",
  "Lider tecnico con experiencia construyendo y gobernando plataformas cloud sobre Azure para equipos de producto, desarrollo y seguridad. Ha coordinado modernizaciones de infraestructura, despliegues CI/CD, observabilidad, automatizacion operativa e iniciativas de confiabilidad para cargas criticas con alcance regional.":
    "Technical leader with experience building and governing cloud platforms on Azure for product, development, and security teams. He has coordinated infrastructure modernizations, CI/CD deployments, observability, operational automation, and reliability initiatives for critical workloads at regional scale.",
  "Lidero una migracion multicuenta en Azure con foco en confiabilidad y estandarizacion DevOps.":
    "I led a multi-account Azure migration focused on reliability and DevOps standardization.",
  "Tasa de desempleo": "Unemployment Rate",
  "Tras la caída postpandemia, enero de 2026 muestra un repunte estacional frente al promedio anual de 2025.":
    "After the post-pandemic decline, January 2026 shows a seasonal rebound versus the 2025 annual average.",
  "Tasa de ocupación": "Employment Rate",
  "Tasa de ocupacion": "Employment Rate",
  "Recuperación sostenida tras la pandemia, con ajuste estacional al iniciar enero de 2026.":
    "Steady recovery after the pandemic, with a seasonal adjustment at the start of January 2026.",
  "Variación anual del desempleo": "Annual Unemployment Change",
  "Variacion anual del desempleo": "Annual Unemployment Change",
  "Tras varios años de mejora, enero de 2026 muestra un repunte estacional frente al nivel promedio de 2025.":
    "After several years of improvement, January 2026 shows a seasonal increase relative to the 2025 average level.",
  "Comparación anual del desempleo": "Year-on-year comparison of unemployment",
  "Comparacion anual del desempleo": "Year-on-year comparison of unemployment",
  "Lectura anual del desempleo con su variación frente al año previo.":
    "Annual unemployment reading with its change compared with the previous year.",
  "Tasa y cambio anual": "Rate and annual change",
  "2020 (choque fuerte)": "2020 (severe shock)",
  "Cierre de empresas, cuarentenas y caida de la actividad economica. Resultado: perdida masiva de empleos.":
    "Business closures, quarantines, and a drop in economic activity. Result: massive job losses.",
  "2021-2023 (recuperacion rapida)": "2021-2023 (rapid recovery)",
  "2021-2023 (recuperación rápida)": "2021-2023 (rapid recovery)",
  "Reactivacion economica, reapertura de sectores y regreso de trabajadores. Resultado: baja fuerte del desempleo.":
    "Economic reactivation, sector reopening, and the return of workers. Result: a sharp drop in unemployment.",
  "2024-2025 (mejora moderada)": "2024-2025 (moderate improvement)",
  "Cierre de empresas, cuarentenas y caída de la actividad económica. Resultado: pérdida masiva de empleos.":
    "Business closures, quarantines, and a drop in economic activity. Result: massive job losses.",
  "Reactivación económica, reapertura de sectores y regreso de trabajadores. Resultado: fuerte caída del desempleo.":
    "Economic reactivation, sector reopening, and the return of workers. Result: a sharp drop in unemployment.",
  "El empleo sigue creciendo, pero más lento. Resultado: menor reducción del desempleo y estabilización.":
    "Employment keeps growing, but more slowly. Result: a smaller reduction in unemployment and greater stability.",
  "2026 (repunte estacional)": "2026 (seasonal rebound)",
  "En enero terminan empleos temporales de fin de año. Resultado: aumento del desempleo de forma estacional.":
    "Temporary year-end jobs end in January. Result: unemployment rises for seasonal reasons.",
  "El empleo sigue creciendo, pero mas lento. Resultado: menos impulso economico y mayor estabilidad.":
    "Employment keeps growing, but more slowly. Result: less economic momentum and greater stability.",
  "2026 (repunte inicial)": "2026 (initial uptick)",
  "En enero se terminan empleos temporales de navidad. Resultado: sube el desempleo de forma estacional.":
    "Temporary Christmas jobs end in January. Result: unemployment rises seasonally.",
  "Jobs activas": "Active Jobs",
  "Jobs activas simultaneas con historico anual 2020-2025.":
    "Simultaneous active job postings with annual history from 2020 to 2025.",
  "Nivel educativo más demandado": "Most in-demand educational level",
  "Nivel educativo mas demandado": "Most in-demand educational level",
  "Evolución del nivel educativo más solicitado entre 2020 y 2026.":
    "Evolution of the most requested education level between 2020 and 2026.",
  "Evolucion del nivel educativo mas solicitado entre 2020 y 2026.":
    "Evolution of the most requested education level between 2020 and 2026.",
  "Ocupaciones más demandadas": "Most in-demand occupations",
  "Ocupaciones mas demandadas": "Most in-demand occupations",
  "Roles con mayor frecuencia en las jobs activas.":
    "Roles most frequently found in active job postings.",
  "Empresas con más ofertas": "Companies with the most job openings",
  "Empresas con mas ofertas": "Companies with the most job openings",
  "Empresas más visible por volumen de contratación en cada etapa.":
    "Companies most visible by volume of hiring at each stage.",
  "Empresas mas visibles por volumen de contratacion en cada etapa.":
    "Companies most visible by volume of hiring at each stage.",
  "Sectores con más jobs": "Sectors with the most jobs",
  "Sectores con mas jobs": "Sectors with the most jobs",
  "Evolución anual de los sectores con mayor presencia en el mercado.":
    "Annual evolution of the sectors with the strongest market presence.",
  "Evolucion anual de los sectores con mayor presencia en el mercado.":
    "Annual evolution of the sectors with the strongest market presence.",
  "Skills más solicitadas": "Most requested skills",
  "Skills mas solicitadas": "Most requested skills",
  "Skills blandas, tecnicas y operativas con mayor recurrencia.":
    "Soft, technical, and operational skills are most frequently required.",
  "Condiciones laborales": "Working conditions",
  "Summary anual de contratos, modalidad, salarios y estabilidad laboral.":
    "Annual summary of contracts, work mode, salaries, and job stability.",
  "Resumen anual de contratos, modalidad, salarios y estabilidad laboral.":
    "Annual summary of contracts, work mode, salaries, and job stability.",
  "Salario promedio": "Average salary",
  "Ingreso promedio mensual estimado del mercado laboral.":
    "Estimated average monthly income in the labor market.",
  "Salario real vs inflación": "Real salary vs inflation",
  "Salario real vs inflacion": "Real salary vs inflation",
  "Cambio del salario real frente a la inflación anual.":
    "Change in real salary versus annual inflation.",
  "Cambio del salario real frente a la inflacion anual.":
    "Change in real salary versus annual inflation.",
  "Porcentaje de Jobs por Rango Salarial": "Percentage of jobs by salary range",
  "Distribución de jobs por rango salarial en Colombia.":
    "Distribution of jobs by salary range in Colombia without transportation and food assistance.",
  "Distribucion de jobs por rango salarial en Colombia.":
    "Distribution of jobs by salary range in Colombia without transportation and food assistance.",
  "Historial de salario mínimo": "Minimum wage history",
  "Historial de salario minimo": "Minimum wage history",
  "Evolución del salario mínimo legal en Colombia.":
    "Evolution of the legal minimum wage in Colombia.",
  "Evolucion del salario minimo legal en Colombia.":
    "Evolution of the legal minimum wage in Colombia.",
  "Salario por sector": "Salary by sector",
  "Comparativa de rangos salariales por sector.":
    "Comparison of salary ranges by sector.",
  "Sectores mejor pagados": "Best-paid sectors",
  "Sectores intermedios": "Mid-range sectors",
  "Sectores con menores salarios": "Lower-paid sectors",
  "Salario por experiencia laboral": "Salary by work experience",
  "Rangos salariales según years de experiencia y nivel de responsabilidad.":
    "Salary ranges by years of experience and level of responsibility.",
  "Rangos salariales según años de experiencia y nivel de responsabilidad.":
    "Salary ranges by years of experience and level of responsibility.",
  "Dónde están las oportunidades reales": "Where the real opportunities are",
  "Donde estan las oportunidades reales": "Where the real opportunities are",
  "Relación entre el volumen de jobs y la calidad salarial del mercado.":
    "Relationship between job volume and market wage quality.",
  "Relacion entre el volumen de jobs y la calidad salarial del mercado.":
    "Relationship between job volume and market wage quality.",
  "Demanda laboral (MinTrabajo – SPE)": "Labor demand (Ministry of Labor - SPE)",
  "Sectores con más jobs: comercio, servicios e industria":
    "Sectors with the most jobs: commerce, services, and industry",
  "Más del 40% del empleo total está en comercio y servicios":
    "More than 40% of total employment is in commerce and services",
  "Mas del 40% del empleo total esta en comercio y servicios":
    "More than 40% of total employment is in commerce and services",
  "Salario (DANE – GEIH)": "Salary (DANE - GEIH)",
  "Ingreso laboral mediano (2023–2025): alrededor de 1,2M a 1,5M":
    "Median labor income (2023-2025): around 1.2M to 1.5M",
  "La mayoría de trabajadores gana entre 1 y 2 salarios mínimos":
    "Most workers earn between 1 and 2 minimum wages",
  "La mayoria de trabajadores gana entre 1 y 2 salarios minimos":
    "Most workers earn between 1 and 2 minimum wages",
  "Dato clave integrado": "Integrated key data",
  "Alta demanda: comercio y servicios concentran más del 40% del empleo, pero con ingresos bajos cercanos al mínimo.":
    "High demand: commerce and services account for more than 40% of employment, but with low incomes close to the minimum wage.",
  "Alta demanda: comercio y servicios concentran mas del 40% del empleo, pero con ingresos bajos cercanos al minimo.":
    "High demand: commerce and services account for more than 40% of employment, but with low incomes close to the minimum wage.",
  "Tecnología y finanzas tienen menor volumen de vacantes, pero mejores salarios.":
    "Technology and finance have lower job volume, but better salaries.",
  "Tecnologia y finanzas tienen menor volumen de vacantes, pero mejores salarios.":
    "Technology and finance have lower job volume, but better salaries.",
  "La mayoría del empleo se concentra en sectores de baja remuneración y baja experiencia.":
    "Most employment is concentrated in low-paying, low-experience sectors.",
  "La mayoria del empleo se concentra en sectores de baja remuneracion y baja experiencia.":
    "Most employment is concentrated in low-paying, low-experience sectors.",
  "Tendencia del mercado laboral en 2026": "Labor market trend in 2026",
  "Lectura compacta del mercado actual, sus requisitos y el pronóstico inmediato.":
    "Compact reading of the current market, its requirements, and the immediate outlook.",
  "Lectura compacta del mercado actual, sus requisitos y el pronostico inmediato.":
    "Compact reading of the current market, its requirements, and the immediate outlook.",
  "Situación general": "General Situation",
  "Situacion general": "General Situation",
  "Desempleo 2025: ~9,0%": "Unemployment 2025: ~9.0%",
  "Enero 2026: 10,9%": "January 2026: 10.9%",
  "Proyección 2026: ~9% promedio anual": "2026 Projection: ~9% annual average",
  "Proyeccion 2026: ~9% promedio anual": "2026 Projection: ~9% annual average",
  "Mercado en recuperación, pero todavía inestable": "Market in recovery, but still unstable",
  "Mercado en recuperacion, pero todavia inestable": "Market in recovery, but still unstable",
  "Puestos más solicitados": "Most Requested Roles",
  "Puestos mas solicitados": "Most Requested Roles",
  "Predominan cargos operativos y de alta rotación": "Operational and high-turnover roles predominate",
  "Predominan cargos operativos y de alta rotacion": "Operational and high-turnover roles predominate",
  "Salarios más comunes": "Most Common Salaries",
  "Salarios mas comunes": "Most Common Salaries",
  "La mayor parte de jobs se mueve en rangos salariales bajos y medios":
    "Most jobs fall within low and medium salary ranges",
  "Requisitos y experiencia": "Requirements and Experience",
  "Procesos más rápidos y competitivos": "Faster and More Competitive Processes",
  "Procesos mas rapidos y competitivos": "Faster and More Competitive Processes",
  "Problemas del mercado": "Market challenges",
  "Persisten brechas de calidad salarial e informalidad":
    "Wage quality and informality gaps persist",
  "Alta concentración en empleos operativos y de menor productividad":
    "High concentration in operational and lower-productivity jobs",
  "Alta concentracion en empleos operativos y de menor productividad":
    "High concentration in operational and lower-productivity jobs",
  "Sigue habiendo distancia entre volumen de vacantes y mejores salarios":
    "A gap remains between job volume and better salaries",
  "Pronóstico 2026–2027": "Outlook 2026-2027",
  "Pronostico 2026–2027": "Outlook 2026-2027",
  "Comercio, servicios y logística seguirán liderando en volumen":
    "Commerce, services, and logistics will continue to lead in volume",
  "Comercio, servicios y logistica seguiran liderando en volumen":
    "Commerce, services, and logistics will continue to lead in volume",
  "Tecnología, finanzas y energía mantendrán mejores rangos salariales":
    "Technology, finance, and energy will maintain better salary ranges",
  "Tecnologia, finanzas y energia mantendran mejores rangos salariales":
    "Technology, finance, and energy will maintain better salary ranges",
  "Mayor uso de IA y herramientas digitales": "Greater use of AI and digital tools",
  "Retos: talento especializado, costos laborales e informalidad":
    "Challenges: specialized talent, labor costs, and informality",
  "Experiencia promedio requerida": "Average experience required",
  "Evolución de la experiencia requerida según el comportamiento reciente del mercado.":
    "Evolution of required experience according to recent market behavior.",
  "Evolucion de la experiencia requerida segun el comportamiento reciente del mercado.":
    "Evolution of required experience according to recent market behavior.",
  "Evolución de la experiencia requerida (2020–2026)":
    "Evolution of required experience (2020-2026)",
  "Evolucion de la experiencia requerida (2020–2026)":
    "Evolution of required experience (2020-2026)",
  "Lectura del mercado": "Market reading",
  "La experiencia exigida se mantiene baja en general (0–2 years), con una tendencia hacia perfiles junior. En 2025 se observa una apertura a perfiles sin experiencia, seguida de un retorno a niveles de 1–2 years en 2026.":
    "Required experience remains generally low (0-2 years), with a tilt toward junior profiles. In 2025 the market opened up to candidates with no experience, followed by a return to 1-2 year levels in 2026.",
  "La experiencia exigida se mantiene baja en general (0–2 años), con una tendencia hacia perfiles junior. En 2025 se observa una apertura a perfiles sin experiencia, seguida de un retorno a niveles de 1–2 años en 2026.":
    "Required experience remains generally low (0-2 years), with a tilt toward junior profiles. In 2025 the market opened up to candidates with no experience, followed by a return to 1-2 year levels in 2026.",
  "Modalidad de trabajo": "Work mode",
  "Distribución visible entre formatos de trabajo.": "Visible distribution across work formats.",
  "Distribucion visible entre formatos de trabajo.": "Visible distribution across work formats.",
  "Certificaciones y herramientas": "Certifications and tools",
  "Certificaciones y herramientas más comunes por áreas del mercado.":
    "Most common certifications and tools by market area.",
  "Certificaciones y herramientas mas comunes por areas del mercado.":
    "Most common certifications and tools by market area.",
  "Ingeniería y tecnología": "Engineering and technology",
  "Ingenieria y tecnologia": "Engineering and technology",
  "Administración, contabilidad y finanzas": "Administration, accounting, and finance",
  "Administracion, contabilidad y finanzas": "Administration, accounting, and finance",
  "Comercio, ventas y marketing": "Commerce, sales, and marketing",
  "Logística, industria y construcción": "Logistics, industry, and construction",
  "Logistica, industria y construccion": "Logistics, industry, and construction",
  "Educación y formación": "Education and training",
  "Educacion y formacion": "Education and training",
  "Entidades clave": "Key institutions",
  "Certificaciones": "Certifications",
  "Herramientas": "Tools",
  "Skills blandas": "Soft, technical and operational skills",
  "Skills técnicas": "Soft, technical and operational skills",
  "Skills tecnicas": "Soft, technical and operational skills",
  "Skills operativas": "Soft, technical and operational skills",
  "Servicio al cliente / call center": "Customer service / call center",
  "Ventas y asesores comerciales": "Sales and commercial advisors",
  "Auxiliares administrativos y de oficina": "Administrative and office assistants",
  "Operarios y produccion": "Production and plant workers",
  "Logistica": "Logistics",
  "Construccion": "Construction",
  "Salud": "Healthcare",
  "Tecnologia": "Technology",
  "Contabilidad y finanzas": "Accounting and finance",
  "Marketing digital y comercio electronico": "Digital marketing and e-commerce",
  "Seguridad (vigilantes, guardas de seguridad)": "Security (watchmen, security guards)",
  "Educacion (docentes, instructores, formacion tecnica)":
    "Education (teachers, instructors, technical training)",
  "Comunicación efectiva": "Effective communication",
  "Comunicacion efectiva": "Effective communication",
  "Trabajo en equipo": "Teamwork",
  "Responsabilidad y puntualidad": "Responsibility and punctuality",
  "Adaptabilidad": "Adaptability",
  "Orientación al cliente": "Customer orientation",
  "Orientacion al cliente": "Customer orientation",
  "Manejo de herramientas digitales (Excel, Office)":
    "Use of digital tools (Excel, Office)",
  "Atención al cliente / CRM": "Customer service / CRM",
  "Atencion al cliente / CRM": "Customer service / CRM",
  "Ventas y negociación": "Sales and negotiation",
  "Ventas y negociacion": "Sales and negotiation",
  "Logística e inventarios": "Logistics and inventory",
  "Logistica e inventarios": "Logistics and inventory",
  "Programación y soporte TI": "Scheduling and Support IT",
  "Programacion y soporte TI": "Scheduling and Support IT",
  "Manejo de maquinaria o equipos": "Operation of machinery or equipment",
  "Procesos de producción": "Production processes",
  "Procesos de produccion": "Production processes",
  "Conducción (licencias específicas)": "Driving (specific licenses)",
  "Conduccion (licencias especificas)": "Driving (specific licenses)",
  "Manipulación de alimentos": "Food handling",
  "Manipulacion de alimentos": "Food handling",
  "Pandemia": "Pandemic",
  "Contratos temporales o suspendidos": "Temporary or suspended contracts",
  "Reducción de salarios en algunos sectores": "Salary reductions in some sectors",
  "Reduccion de salarios en algunos sectores": "Salary reductions in some sectors",
  "Auge del teletrabajo": "Rise of remote work",
  "Alta informalidad": "High informality",
  "Recuperar puestos de trabajo": "Recover jobs",
  "Reactivación": "Recovery",
  "Reactivacion": "Recovery",
  "Contratos a término fijo predominan": "Fixed-term contracts predominate",
  "Contratos a termino fijo predominan": "Fixed-term contracts predominate",
  "Regreso progresivo a presencialidad": "Gradual return to on-site work",
  "Salarios aún bajos en muchos sectores": "Salaries still low in many sectors",
  "Salarios aun bajos en muchos sectores": "Salaries still low in many sectors",
  "Normalización del mercado laboral": "Normalization of the labor market",
  "Incremento del salario mínimo y leve ajuste en salarios generales":
    "Minimum wage increase and a slight adjustment in overall wages",
  "Normalizacion del mercado laboral": "Normalization of the labor market",
  "Recuperación fuerte": "Strong recovery",
  "Recuperacion fuerte": "Strong recovery",
  "Más contratos formales": "More formal contracts",
  "Mas contratos formales": "More formal contracts",
  "Mejora en estabilidad laboral": "Improved job stability",
  "Incremento leve en salarios": "Slight salary increase",
  "Equilibrio laboral": "Labor balance",
  "Estabilización": "Stabilization",
  "Estabilizacion": "Stabilization",
  "Predominio de contratos formales (fijo e indefinido)":
    "Predominance of formal contracts (fixed-term and permanent)",
  "Mayor exigencia de experiencia": "Higher experience requirements",
  "Beneficios básicos (seguridad social)": "Basic benefits (social security)",
  "Beneficios basicos (seguridad social)": "Basic benefits (social security)",
  "Eficiencia empresarial": "Business efficiency",
  "Menor dinamismo": "Lower dynamism",
  "Contratación más selectiva": "More selective hiring",
  "Contratacion mas selectiva": "More selective hiring",
  "Salarios crecen poco frente a inflación": "Salaries grow little compared with inflation",
  "Salarios crecen poco frente a inflacion": "Salaries grow little compared with inflation",
  "Modalidad híbrida en algunos sectores": "Hybrid work mode in some sectors",
  "Modalidad hibrida en algunos sectores": "Hybrid work mode in some sectors",
  "Retención de talento": "Talent retention",
  "Retencion de talento": "Talent retention",
  "Consolidación": "Consolidation",
  "Consolidacion": "Consolidation",
  "Más contratos indefinidos en sectores formales":
    "More permanent contracts in formal sectors",
  "Mas contratos indefinidos en sectores formales":
    "More permanent contracts in formal sectors",
  "Mayor demanda de habilidades digitales": "Higher demand for digital skills",
  "Beneficios adicionales en empresas grandes": "Additional benefits in large companies",
  "Estabilidad con brechas": "Stability with gaps",
  "Actual": "Current",
  "Estabilidad con desaceleración": "Stability with slowdown",
  "Estabilidad general con desaceleración del empleo formal":
    "General stability with a slowdown in formal employment",
  "Empresas tecnológicas": "Technology companies",
  "Consumo y servicios": "Consumption and services",
  "Servicios y comercio": "Services and commerce",
  "Tecnología (en crecimiento)": "Technology (growing)",
  "Tecnología (aún con menor volumen)": "Technology (still lower in volume)",
  "Estabilidad en condiciones laborales": "Stability in working conditions",
  "Combinación de presencial + remoto": "Combination of on-site + remote work",
  "Combinacion de presencial + remoto": "Combination of on-site + remote work",
  "Persisten brechas de informalidad": "Informality gaps persist",
  "Bajos salarios en empleos operativos": "Low wages in operational roles",
  "Realidad": "Reality",
  "Bachiller": "Mid school",
  "Bachiller + tecnico": "Mid school + technical",
  "Técnico y tecnólogo": "Technical and technologist education",
  "Tecnico y tecnologo": "Technical and technologist education",
  "Bachiller / tecnico / profesional": "High school / technical / professional",
  "Bachiller / technical / profesional": "High school / technical / professional",
  "Técnico/tecnólogo + profesional": "Technical/technological + professional",
  "Tecnico/tecnologo + profesional": "Technical/technological + professional",
  "Técnicos/tecnólogos + profesionales": "Technical/technological + professional",
  "Bachiller, técnico y profesional": "High school, technical, and professional",
  "Predominan perfiles técnicos y operativos, con menor peso relativo de profesionales en volumen de vacantes.":
    "Technical and operational profiles predominate, with professionals carrying a smaller relative share of total vacancy volume.",
  "El mercado laboral está dominado por roles operativos y comerciales, con alta rotación y menores salarios, mientras que los empleos mejor remunerados tienen menor volumen de vacantes.":
    "The labor market is dominated by operational and commercial roles, with high turnover and lower wages, while better-paid jobs have lower vacancy volume.",
  "Tecnicos/tecnologos + profesionales": "Technical/technological + professional",
  "Empresas esenciales": "Essential companies",
  "Reapertura y contratación masiva": "Reopening and mass hiring",
  "Reapertura y contratacion masiva": "Reopening and mass hiring",
  "Alto volumen de jobs": "High volume of work",
  "Empleo más formal y estable": "More formal and stable employment",
  "Empleo mas formal y estable": "More formal and stable employment",
  "Volumen constante": "Stable volume",
  "Estabilidad + digitalización": "Stability + digitalization",
  "Estabilidad + digitalizacion": "Stability + digitalization",
  "Light": "Current snapshot",
  "Logística y retail": "Logistics and retail",
  "Logistica y retail": "Logistics and retail",
  "Sectores esenciales": "Essential sectors",
  "Reapertura económica": "Economic reopening",
  "Reapertura economica": "Economic reopening",
  "Crecimiento económico alto": "High economic growth",
  "Crecimiento economico alto": "High economic growth",
  "Comercio y ventas": "Commerce and sales",
  "Industria / manufactura": "Industry / manufacturing",
  "Logística y transporte": "Logistics and transportation",
  "Logistica y transporte": "Logistics and transportation",
  "Mercado más equilibrado": "More balanced market",
  "Mercado mas equilibrado": "More balanced market",
  "Administrativo": "Administrative",
  "Estabilidad con menor crecimiento": "Stability with lower growth",
  "Digitalización + consumo": "Digitalization + consumption",
  "Digitalizacion + consumo": "Digitalization + consumption",
  "Comercio y retail": "Commerce and retail",
  "Equilibrio + transformación digital": "Balance + digital transformation",
  "Equilibrio + transformacion digital": "Balance + digital transformation",
  "De 1M a 2M": "From 1M to 2M",
  "De 2M a 3M": "From 2M to 3M",
  "De 3M a 4M": "From 3M to 4M",
  "De 4M a 5M": "From 4M to 5M",
  "Mas de 5M": "More than 5M",
  "Financiero": "Finance",
  "Energía / minería": "Energy / mining",
  "Energia / mineria": "Energy / mining",
  "Operación y perfiles especializados.": "Operations and specialized profiles.",
  "Operacion y perfiles especializados.": "Operations and specialized profiles.",
  "Operación y supervisión.": "Operations and supervision.",
  "Operacion y supervision.": "Operations and supervision.",
  "Obra y apoyo technical.": "Work and technical support.",
  "Obra y apoyo tecnico.": "Work and technical support.",
  "Muy variable según profesión.": "Highly variable depending on the profession.",
  "Muy variable segun profesion.": "Highly variable depending on the profession.",
  "Ventas y retail.": "Sales and retail.",
  "Call center y restaurantes.": "Call centers and restaurants.",
  "Perfiles operativos.": "Operational profiles.",
  "Primer empleo o poca experiencia": "First job or little experience",
  "Alta rotación": "High turnover",
  "Alta rotacion": "High turnover",
  "Común en ventas, atención y auxiliares": "Common in sales, support, and assistant roles",
  "Comun en ventas, atencion y auxiliares": "Common in sales, support, and assistant roles",
  "Mayor responsabilidad": "Greater responsibility",
  "Manejo de procesos o equipos pequeños": "Management of processes or small teams",
  "Más estabilidad laboral": "More job stability",
  "Mas estabilidad laboral": "More job stability",
  "Alta especialización": "High specialization",
  "Alta especializacion": "High specialization",
  "Toma de decisiones": "Decision-making",
  "Liderazgo o roles técnicos avanzados": "Leadership or advanced technical roles",
  "Liderazgo o roles tecnicos avanzados": "Leadership or advanced technical roles",
  "Directivos / expertos": "Executives / experts",
  "Gerentes y directores": "Managers and directors",
  "Alta responsabilidad estratégica": "High strategic responsibility",
  "Alta responsabilidad estrategica": "High strategic responsibility",
  "Referencia SPE": "SPE reference",
  "Trabajo en alturas": "Working at heights",
  "Licencias de conducción": "Driver's licenses",
  "Licencias de conduccion": "Driver's licenses",
  "Herramientas digitales educativas": "Digital education tools",
  "Cursos SENA en salud": "SENA health courses",
  "Certificaciones clínicas": "Clinical certifications",
  "Certificaciones clinicas": "Clinical certifications",
  "Sistemas hospitalarios": "Hospital systems",
  "Historias clínicas": "Medical records",
  "Historias clinicas": "Medical records",
  "Sistemas de inventario": "Inventory systems",
  "Maquinaria y equipos": "Machinery and equipment",
  "Software logístico": "Logistics software",
  "Software logistico": "Logistics software",
  "Licenciaturas / formación pedagógica": "Bachelor's degrees / teacher training",
  "Licenciaturas / formacion pedagogica": "Bachelor's degrees / teacher training",
  "Cursos SENA e instituciones": "SENA courses and institutions",
  "Universidades": "Universities",
  "Coursera / LinkedIn Learning": "Coursera/LinkedIn Learning",
  "NIIF": "IFRS",
  "Certificaciones bancarias": "Bank certifications",
  "Software contable": "accounting software",
  "Redes sociales": "Social networks",
  "Plataformas e-commerce": "E-commerce platforms",
  "RCP / primeros auxilios": "CPR/first aid",
  "SENA": "SIGN",
  "Google / Microsoft / Cisco": "Google/Microsoft/Cisco",
  "HubSpot / Google": "HubSpot/Google",
  "Scrum / Agile": "Scrum/Agile",
  "Tecnología (TIC)": "Technology (ICT)",
  "Tecnologia (TIC)": "Technology (ICT)",
  "Banca y seguros.": "Banking and insurance.",
  "Construcción": "Construction",
  "Comercio": "Trade",
  "Servicios": "Services",
  "Logística": "Logistics",
  "Auxiliares administrativos y operativos": "Administrative and Operational Assistants",
  "Logística, construcción y salud": "Logistics, Construction, and Healthcare",
  "Logistica, construccion y salud": "Logistics, Construction, and Healthcare",
  "Tecnología aparece, pero con menor volumen que comercio y servicios":
    "Technology is emerging, but with lower volume than commerce and services",
  "Tecnologia aparece, pero con menor volumen que comercio y servicios":
    "Technology is emerging, but with lower volume than commerce and services",
  "Comunicación, servicio al cliente y manejo digital básico":
    "Communication, Customer Service, and Basic Digital Skills",
  "Comunicacion, servicio al cliente y manejo digital basico":
    "Communication, Customer Service, and Basic Digital Skills",
  "La mayoría sigue pidiendo entre 0 y 2 years de experiencia":
    "The majority still ask for between 0 and 2 years of experience",
  "La mayoría sigue pidiendo entre 0 y 2 años de experiencia":
    "The majority still ask for between 0 and 2 years of experience",
  "La mayoria sigue pidiendo entre 0 y 2 años de experiencia":
    "The majority still ask for between 0 and 2 years of experience",
  "Rango dominante en 2026: 1–2 years": "Dominant rank in 2026: 1-2 years",
  "Rango dominante en 2026: 1–2 años": "Dominant rank in 2026: 1-2 years",
  "Remoto dominante (30–40%)": "Remote dominant (30-40%)",
  "Mixto: remoto + presencial": "Hybrid: remote + on-site",
  "Mixto: remoto + on-site": "Hybrid: remote + on-site",
  "Presencial vuelve a liderar (~70%)": "In-person returns to the lead (~70%)",
  "Presencial ~75% + híbrido en aumento": "In-person ~75% + hybrid on the rise",
  "Presencial ~75% + hibrido en aumento": "In-person ~75% + hybrid on the rise",
  "Presencial 75–80% · híbrido 15–20%": "In-person 75-80% · hybrid 15-20%",
  "Presencial 75–80% · hibrido 15–20%": "In-person 75-80% · hybrid 15-20%",
  "Presencial 80% · híbrido 15% · remoto 5%": "In-person 80% · hybrid 15% · remote 5%",
  "Presencial 80% · hibrido 15% · remoto 5%": "In-person 80% · hybrid 15% · remote 5%",
  "Presencial 80–85% · híbrido 10–15% · remoto 5%": "In-person 80-85% · hybrid 10-15% · remote 5%",
  "Presencial 80–85% · hibrido 10–15% · remoto 5%": "In-person 80-85% · hybrid 10-15% · remote 5%",
  "Alta oportunidad": "High opportunity",
  "Tecnología": "Technology",
  "Competitivo": "Competitive",
  "Saturado": "Saturated",
  "Comercio / servicios": "Commerce / Services",
  "General situation": "General Situation",
  "Bachiller + technical o tecnólogo": "High School Diploma + Technical or Technological Degree",
  "Bachiller + technical o tecnologo": "High School Diploma + Technical or Technological Degree",
};
