export const PHRASE_MAP_CORE: Record<string, string> = {
  "Iniciar sesión": "Log in",
  "Iniciar sesion": "Log in",
  "Cerrar sesión": "Log out",
  "Cerrar sesion": "Log out",
  "Modo oscuro": "Dark mode",
  "Modo claro": "Light mode",
  "Buscar ofertas": "Search jobs",
  "Buscar ofertas...": "Search jobs...",
  "Aplicar filtros": "Apply filters",
  "Limpiar filtros": "Clear filters",
  "Marcar todo como leido": "Mark all as read",
  "Marcar todas como leidas": "Mark all as read",
  "Marcar como no leido": "Mark as unread",
  "Marcar como no leida": "Mark as unread",
  "Marcar como leido": "Mark as read",
  "Marcar como leida": "Mark as read",
  "Notificaciones": "Notifications",
  "Empresas": "Companies",
  "Plataforma": "Platform",
  "Filtros": "Filters",
  "Resultados": "Results",
  "Atras": "Back",
  "Inicio": "Home",
  "Ofertas": "Jobs",
  "Mi perfil": "My profile",
  "Ajustes": "Settings",
  "Claro": "Light",
  "Oscuro": "Dark",
  "Completa tu perfil para aplicar": "Complete your profile to apply",
  "Completa tu perfil para aplicar (30 segundos)": "Complete your profile to apply (30 seconds)",
  "Guardar cambios": "Save changes",
  "Perfil actual": "Current profile",
  "completo": "complete",
  "Despues": "Later",
  "Completar perfil": "Complete profile",
  "Detalle del perfil": "Profile details",
  "Detalle de la oferta": "Offer details",
  "Resumen del candidato": "Candidate summary",
  "Perfil completo del candidato": "Full candidate profile",
  "Resumen de la oferta": "Offer summary",
  "Aplicar": "Apply",
  "Ver resumen": "View summary",
  "Cerrar": "Close",
  "Ver perfil": "See Profile",
  "Perfil profesional": "Professional profile",
  "Empresa": "Company",
  "Empresa confidencial": "Confidential company",
  "Perfil visible": "Visible profile",
  "Beneficios extra": "Extra benefits",
  "Experiencia requerida": "Required experience",
  "Experiencia del perfil": "Profile experience",
  "Aspiracion salarial": "Salary expectation",
  "Salario a pagar": "Salary to pay",
  "Disponibilidad": "Availability",
  "No especificados": "Not specified",
  "Notificaciones de empresas desactivadas.": "Company notifications are disabled.",
  "Notificaciones de plataforma desactivadas.": "Platform notifications are disabled.",
  "Trending por tus búsquedas": "Trending for your searches",
  "Modalidad": "Work mode",
  "Publicador": "Publisher",
  "Urgente": "Urgent",
  "Departamento": "Department",
  "Municipio": "City",
  "Categoría": "Category",
  "Fecha": "Date",
  "90 días": "90 days",
  "1 día": "1 day",
  "3 meses": "3 months",
  "Salario mínimo": "Minimum salary",
  "Experiencia laboral": "Work experience",
  "Experiencia": "Experience",
  "1 año": "1 year",
  "10+ años": "10+ years",
  "9 jobs visibles": "9 visible jobs",
  "Señales activas de mercado": "Active market signals",
  "Ordenar por": "Sort by",
  "Aplica hoy": "Apply today",
  "aplicaron": "applied",
  "Vacante backend con NestJS y TypeScript, consumo de APIs REST y SOAP, microservicios, AWS y apoyo en aplicaciones web y moviles dentro de un esquema remoto.": "Backend role with NestJS and TypeScript, REST and SOAP APIs, microservices, AWS, and support for web/mobile apps in a remote setup.",
  "Cargo orientado a liderar y priorizar iniciativas de analitica, maximizando valor para el negocio y alineando roadmap, plazos y calidad con la celula tecnica.": "Role focused on leading and prioritizing analytics initiatives, maximizing business value and aligning roadmap, timelines, and quality with the technical team.",
  "Rol estrategico para potenciar la linea de Google Workspace y evolucionarla hacia servicios consultivos apoyados en IA, automatizacion y transformacion digital.": "Strategic role to strengthen the Google Workspace line and evolve it toward consulting services powered by AI, automation, and digital transformation.",
  "Vacante orientada a SEO tecnico y analitica de buscadores, con manejo de paginas web, consolas, IA aplicada a busqueda y disponibilidad para lanzamientos puntuales.": "Role focused on technical SEO and search analytics, managing websites, consoles, AI-assisted search, and punctual launch support.",
  "Lider del frente cloud para una compania de tecnologia con foco en infraestructura segura, resiliente y escalable para equipos de producto de alto volumen.": "Lead the cloud area for a technology company focused on secure, resilient, and scalable infrastructure for high-volume product teams.",
  "Rol senior para modernizacion cloud con Azure, AWS u OpenStack, Kubernetes y Terraform, trabajando con equipos regionales y locales de IT.": "Senior role for cloud modernization with Azure, AWS or OpenStack, Kubernetes, and Terraform, working with regional and local IT teams.",
  "Vacante para aseguramiento de calidad con pruebas manuales y automatizadas, integracion continua y colaboracion cercana con equipos de producto e ingenieria.": "QA role with manual and automated testing, continuous integration, and close collaboration with product and engineering teams.",
  "Profile de testing con enfasis en automatizacion, pruebas REST y SOAP para equipos que necesitan cobertura funcional y disciplina de calidad en ciclos agiles.": "Testing profile focused on automation, REST and SOAP testing for teams needing functional coverage and quality discipline in agile cycles.",
  "Cargo para planeacion, ejecucion, control y cierre de proyectos con foco en cronograma, costos, riesgos y coordinacion operativa desde oficina en Bogota.": "Role for planning, execution, control, and project closure focused on schedule, costs, risks, and operational coordination from Bogotá office.",
  "Presencial": "On-site",
  "Tiempo completo": "Full time",
  "Interes en 2 dias": "Interest in 2 days",
  "Visibilidad 2 semanas": "Visibility 2 weeks",
  "Atracción de candidatos": "Candidate attraction",
  "Atraccion de candidatos": "Candidate attraction",
  "Sitio web": "Website",
  "Disponibilidad de viaje": "Travel availability",
  "Actualidad": "Present",
  "Nombre completo": "Full name",
  "Rol profesional": "Professional role",
  "Borrar foto": "Delete photo",
  "Campos clave completos": "Completed key fields.",
  "Perfil base estable": "Stable Base Profile",
  "Perfil optimizado": "Optimized Profile",
  "Información básica": "Basic Information",
  "Informacion básica": "Basic Information",
  "Información adicional": "Additional Information",
  "Informacion adicional": "Additional Information",
  "Moto": "Bike",
  "Carro": "Car",
  "Bicicleta": "Bicycle",
  "Camioneta": "Van",
  "Otro": "Other",
  "Completo": "Complete",
  "Editando": "Editing...",
  "Oferta ideal": "Ideal role",
  "Brecha": "Gap",
  "Infraestructura como codigo": "Infrastructure as code",
  "Observabilidad": "Observability",
  "Gobierno tecnico": "Technical governance",
  "Liderazgo de plataforma": "Platform leadership",
  "Alta demanda": "High demand",
  "Español": "Spanish",
  "Inglés": "English",
  "Si": "Yes",
  "Sí": "Yes",
  "No en este momento": "No in this moment",
  "Dentro de poco": "Shortly",
  "Remoto": "Remote",
  "Hibrido": "Hybrid",
  "Medio tiempo": "Part time",
  "Por horas": "Hourly",
  "Turnos rotativos": "Rotating shifts",
  "Lunes a viernes": "Monday to Friday",
  "Fin de semana": "Weekend",
  "Nocturna": "Night shift",
  "Diurna": "Day shift",
  "Busca un idioma": "Search for a language",
  "Busca por NIT o nombre": "Search by tax ID or company name",
  "Fecha inicio": "Start date",
  "Fecha fin": "End date",
};
