import type { LanguageLevelSystem } from "@/types/profile";

export const DEFAULT_LANGUAGE_LEVEL_SYSTEM: LanguageLevelSystem = "CEFR";
export const DEFAULT_LANGUAGE_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2", "Nativo"] as const;

export type LanguageDefinition = {
  name: string;
  levelSystem: LanguageLevelSystem;
  levels: readonly string[];
};

const LANGUAGE_NAME_OPTIONS = [
  "Inglés",
  "Chino mandarín",
  "Hindi",
  "Español",
  "Árabe estándar",
  "Francés",
  "Bengalí",
  "Portugués",
  "Ruso",
  "Indonesio",
  "Urdu",
  "Alemán",
  "Japonés",
  "Punjabi",
  "Maratí",
  "Telugu",
  "Turco",
  "Coreano",
  "Tamil",
  "Vietnamita",
  "Italiano",
  "Persa (farsi)",
  "Tailandés",
  "Gujarati",
  "Polaco",
  "Ucraniano",
  "Malayo",
  "Kannada",
  "Odia",
  "Malayalam",
  "Sundanés",
  "Hausa",
  "Yoruba",
  "Igbo",
  "Amárico",
  "Neerlandés",
  "Rumano",
  "Checo",
  "Griego",
  "Húngaro",
  "Sueco",
  "Finés",
  "Noruego",
  "Danés",
  "Hebreo",
  "Eslovaco",
  "Búlgaro",
  "Croata",
  "Serbio",
  "Catalán",
  "Gallego",
  "Euskera",
  "Filipino (tagalo)",
  "Lao",
  "Khmer",
  "Birmano",
  "Nepalí",
  "Cingalés",
  "Pashto",
  "Kurdo",
  "Azerí",
  "Kazajo",
  "Uzbeko",
  "Turcomano",
  "Mongol",
  "Tibetano",
  "Georgiano",
  "Armenio",
  "Albanés",
  "Macedonio",
  "Esloveno",
  "Letón",
  "Lituano",
  "Estonio",
  "Islandés",
  "Maltés",
  "Irlandés",
  "Galés",
  "Bretón",
  "Luxemburgués",
  "Frisón",
  "Afrikaans",
  "Zulú",
  "Xhosa",
  "Somalí",
  "Tigrinya",
  "Oromo",
  "Swahili",
  "Lingala",
  "Shona",
  "Kinyarwanda",
  "Kirundi",
  "Malagasy",
  "Wolof",
  "Bambara",
  "Fulani",
  "Quechua",
  "Aymara",
  "Guaraní",
  "Náhuatl",
  "Mapudungun",
  "Cree",
  "Inuit",
  "Cherokee",
  "Maya yucateco",
  "Mixteco",
  "Zapoteco",
  "Hmong",
  "Karen",
  "Shan",
  "Uyghur",
  "Dzongkha",
  "Sinhala",
  "Balinés",
  "Javanés",
  "Madurés",
  "Acehnés",
  "Minangkabau",
  "Batak",
  "Cebuano",
  "Ilocano",
  "Waray",
  "Bicolano",
  "Chamorro",
  "Fiyiano",
  "Samoano",
  "Tongano",
  "Maorí",
  "Hawaiano",
  "Tahitiano",
  "Tok Pisin",
  "Papiamento",
  "Criollo haitiano",
  "Criollo caboverdiano",
  "Criollo jamaiquino",
  "Sardo",
  "Siciliano",
  "Napolitano",
  "Occitano",
  "Provenzal",
  "Francoprovenzal",
  "Valón",
  "Lombardo",
  "Piamontés",
  "Véneto",
  "Friulano",
  "Ladino",
  "Romanche",
  "Sami",
  "Komi",
  "Udmurto",
  "Mari",
  "Chuvash",
  "Bashkir",
  "Tártaro",
  "Checheno",
  "Ingusetio",
  "Avar",
  "Lezgiano",
  "Dargwa",
  "Kabardiano",
  "Osetio",
  "Abjasio",
  "Adigué",
  "Yakuto (saja)",
  "Evenki",
  "Nenets",
  "Kalmyk",
  "Buriato",
  "Tuva",
  "Khanty",
  "Mansi",
  "Nivkh",
  "Itelmeno",
  "Koryak",
  "Chukchi",
  "Aleutiano",
  "Yupik",
  "Tlingit",
  "Haida",
  "Kwakiutl",
  "Salish",
  "Blackfoot",
  "Ojibwa",
  "Dakota",
  "Lakota",
  "Navajo",
  "Apache",
  "Hopi",
  "Zuni",
  "Pima",
  "Tarahumara",
  "Huichol",
  "Totonaco",
  "Mazahua",
  "Otomí",
  "Purepecha",
  "Tzeltal",
  "Tzotzil",
  "Chontal",
  "Ch’ol",
  "Kaqchikel",
  "K’iche’",
  "Q’eqchi’",
  "Garífuna",
  "Miskito",
  "Bribri",
  "Cabécar",
  "Kuna",
  "Emberá",
  "Warao",
  "Yanomami",
  "Ticuna",
  "Shipibo",
  "Asháninka",
  "Aguaruna",
  "Bora",
  "Huitoto",
  "Yagua",
  "Guajiro (Wayuu)",
  "Piaroa",
  "Mapuche",
  "Tehuelche",
  "Selk’nam",
  "Kawésqar",
  "Yaghan",
  "Ainu",
  "Naxi",
  "Yi (nuosu)",
  "Zhuang",
  "Hakka",
  "Wu (chino)",
  "Gan",
  "Xiang",
  "Jin",
  "Min del norte",
  "Min del sur",
  "Teochew",
  "Hainanés",
  "Dungan",
  "Salar",
  "Dongxiang",
  "Bonan",
  "Yugur",
  "Tujia",
  "Bai",
  "Lisu",
  "Lahu",
  "Wa",
  "Jingpho",
  "Karen (sgaw)",
  "Karen (pwo)",
  "Mon",
  "Khmer del norte",
  "Cham",
  "Jarai",
  "Ede",
  "Bahnar",
  "Sedang",
  "Katu",
  "Bru",
  "Hre",
  "Mnong",
  "Stieng",
  "Chamicuro",
  "Palikur",
  "Karipuna",
  "Makushi",
  "Wapishana",
  "Trio",
  "Wayana",
  "Lokono",
  "Arawak",
  "Carib",
  "Tupi",
  "Guató",
  "Xavante",
  "Kayapó",
  "Panará",
  "Suruí",
  "Mundurukú",
  "Nambikwara",
  "Bororo",
  "Maxakalí",
  "Tikuna (variante)",
  "Cofán",
  "Siona",
  "Secoya",
  "Shuar",
  "Achuar",
  "Candoshi",
  "Urarina",
  "Movima",
  "Itonama",
  "Cayubaba",
  "Baure",
  "Mosetén",
  "Tacana",
  "Ese Ejja",
  "Cavineña",
  "Wayuunaiki",
  "Curripaco",
  "Piapoco",
  "Damana",
  "Kogui",
  "Wiwa",
  "Tunebo",
  "Tucano",
  "Desano",
  "Cubeo",
  "Sikuani",
  "Guayabero",
  "Wounaan",
  "Nasa Yuwe",
  "Misak",
  "Inga",
  "Kamentsá",
  "Andoke",
  "Coreguaje",
  "Yukpa",
  "Barí",
  "Achagua",
  "Carijona",
  "Ocaina",
  "Nonuya",
  "Miraña",
  "Tanimuka",
  "Letuama",
  "Tatuyo",
  "Siriano",
  "Pisamira",
  "Macuna",
  "Barasana",
  "Palenquero",
  "Criollo sanandresano",
  "Árabe",
  "Chino",
] as const;

export const LANGUAGE_LEVEL_PRESETS: Record<string, Omit<LanguageDefinition, "name">> = {
  "Japonés": {
    levelSystem: "JLPT",
    levels: ["N5", "N4", "N3", "N2", "N1", "Nativo"],
  },
  "Chino mandarín": {
    levelSystem: "HSK",
    levels: ["HSK1", "HSK2", "HSK3", "HSK4", "HSK5", "HSK6", "Nativo"],
  },
  "Coreano": {
    levelSystem: "TOPIK",
    levels: ["TOPIK1", "TOPIK2", "TOPIK3", "TOPIK4", "TOPIK5", "TOPIK6", "Nativo"],
  },
};

export const LANGUAGE_DEFINITIONS: LanguageDefinition[] = LANGUAGE_NAME_OPTIONS.map((name) => ({
  name,
  levelSystem: LANGUAGE_LEVEL_PRESETS[name]?.levelSystem ?? DEFAULT_LANGUAGE_LEVEL_SYSTEM,
  levels: [...(LANGUAGE_LEVEL_PRESETS[name]?.levels ?? DEFAULT_LANGUAGE_LEVELS)],
}));

export const COLOMBIA_LANGUAGE_OPTIONS = LANGUAGE_DEFINITIONS.map((language) => language.name);

function toLanguageCode(name: string) {
  return name
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z]/g, "")
    .slice(0, 12);
}

export function createLanguageCode(name: string) {
  return toLanguageCode(name);
}

export function getLanguageDefinition(name: string) {
  return (
    LANGUAGE_DEFINITIONS.find((language) => language.name === name) ?? {
      name,
      levelSystem: DEFAULT_LANGUAGE_LEVEL_SYSTEM,
      levels: [...DEFAULT_LANGUAGE_LEVELS],
    }
  );
}
